import { LabelDefinition } from "./label-types";
export const DESKTOP_LABELS: LabelDefinition[] = [
    {
        id: "solar",
        title: "SOL",
        icon: "solar",
        x: 760,
        y: 150,
        width: 180,
        height: 110,
    },
    {
        id: "grid",
        title: "ELNÄT",
        icon: "grid",
        x: 80,
        y: 390,
        width: 180,
        height: 110,
    },
    {
        id: "house",
        title: "HUSET",
        icon: "house",
        x: 760,
        y: 480,
        width: 180,
        height: 110,
    },
    {
        id: "battery",
        title: "BATTERI",
        icon: "battery",
        x: 1120,
        y: 390,
        width: 180,
        height: 110,
    },
    {
        id: "spa",
        title: "SPA",
        icon: "spa",
        x: 550,
        y: 700,
        width: 180,
        height: 110,
    },
    {
        id: "heatpump",
        title: "VÄRMEPUMP",
        icon: "heatpump",
        x: 760,
        y: 800,
        width: 180,
        height: 110,
    },
    {
        id: "appliance",
        title: "VITVAROR",
        icon: "appliance",
        x: 970,
        y: 800,
        width: 180,
        height: 110,
    },
    {
        id: "car",
        title: "BIL",
        icon: "car",
        x: 1200,
        y: 800,
        width: 180,
        height: 110,
    },
];