import { LabelDefinition } from "./label-types";
export const DESKTOP_LABELS: LabelDefinition[] = [
    {
        id: "solar",
        title: "SOLAR",
        icon: "solar",
        x: 890,
        y: 300,
        width: 180,
        height: 110,
        accentColor: "#FFD54A",
    },
    {
        id: "grid",
        title: "GRID",
        icon: "grid",
        x: 480,
        y: 440,
        width: 180,
        height: 110,
        accentColor: "#4FC3F7",
    },
    {
        id: "house",
        title: "HOUSE",
        icon: "house",
        x: 890,
        y: 600,
        width: 180,
        height: 110,
        accentColor: "#FFFFFF",
    },
    {
        id: "battery",
        title: "BATTERY",
        icon: "battery",
        x: 1230,
        y: 440,
        width: 180,
        height: 110,
        accentColor: "#FFFFFF",
    },
    {
        id: "spa",
        title: "SPA",
        icon: "spa",
        x: 565,
        y: 750,
        width: 180,
        height: 110,
        accentColor: "#FF8A65",
    },
    {
        id: "heatpump",
        title: "HEATPUMP",
        icon: "heatpump",
        x: 790,
        y: 850,
        width: 180,
        height: 110,
        accentColor: "#4FC3F7",
    },
    {
        id: "appliance",
        title: "APPLIANCE",
        icon: "appliance",
        x: 1000,
        y: 850,
        width: 180,
        height: 110,
        accentColor: "#FFFFFF",
    },
    {
        id: "car",
        title: "CAR",
        icon: "car",
        x: 1230,
        y: 750,
        width: 180,
        height: 110,
        accentColor: "#81D4FA",
    },
];