import { LabelDefinition } from "./label-types";
export const MOBILE_LABELS: LabelDefinition[] = [
    {
        id: "solar",
        title: "SOL",
        icon: "solar",
        x: 160,
        y: 120,
        width: 110,
        height: 70,
    },
    {
        id: "grid",
        title: "ELNÄT",
        icon: "grid",
        x: 25,
        y: 270,
        width: 110,
        height: 70,
    },
    {
        id: "house",
        title: "HUSET",
        icon: "house",
        x: 160,
        y: 370,
        width: 110,
        height: 70,
    },
    {
        id: "battery",
        title: "BATTERI",
        icon: "battery",
        x: 300,
        y: 270,
        width: 110,
        height: 70,
    },
    {
        id: "spa",
        title: "SPA",
        icon: "spa",
        x: 25,
        y: 550,
        width: 105,
        height: 70,
    },
    {
        id: "heatpump",
        title: "VÄRMEPUMP",
        icon: "heatpump",
        x: 25,
        y: 470,
        width: 105,
        height: 70,
    },
    {
        id: "appliance",
        title: "VITVAROR",
        icon: "appliance",
        x: 300,
        y: 550,
        width: 105,
        height: 70,
    },
    {
        id: "car",
        title: "BIL",
        icon: "car",
        x: 300,
        y: 470,
        width: 105,
        height: 70,
    },
];