import { LabelDefinition } from "./label-types";
export const MOBILE_LABELS: LabelDefinition[] = [
    {
        id: "solar",
        title: "SOLAR",
        icon: "solar",
        x: 160,
        y: 130,
        width: 110,
        height: 70,
        accentColor: "#FFD54A",
    },
    {
        id: "grid",
        title: "GRID",
        icon: "grid",
        x: 25,
        y: 220,
        width: 110,
        height: 70,
        accentColor: "#4FC3F7",
    },
    {
        id: "house",
        title: "HOUSE",
        icon: "house",
        x: 160,
        y: 300,
        width: 110,
        height: 70,
        accentColor: "#FFFFFF",
    },
    {
        id: "battery",
        title: "BATTERY",
        icon: "battery",
        x: 300,
        y: 220,
        width: 110,
        height: 70,
        accentColor: "#FFFFFF",
    },
    {
        id: "spa",
        title: "SPA",
        icon: "spa",
        x: 25,
        y: 460,
        width: 105,
        height: 70,
        accentColor: "#FF8A65",
    },
    {
        id: "heatpump",
        title: "HEATPUMP",
        icon: "heatpump",
        x: 25,
        y: 380,
        width: 105,
        height: 70,
        accentColor: "#4FC3F7",
    },
    {
        id: "appliance",
        title: "APPLIANCE",
        icon: "appliance",
        x: 300,
        y: 460,
        width: 105,
        height: 70,
        accentColor: "#FFFFFF",
    },
    {
        id: "car",
        title: "CAR",
        icon: "car",
        x: 300,
        y: 380,
        width: 105,
        height: 70,
        accentColor: "#81D4FA",
    },
];